[package]
name = "binary_fasta"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }

itertools = "0.14.0"

[dev-dependencies]
assert_cmd = "2"
predicates = "3.1"
tempfile   = "3"